Vagrant.configure('2') do |config|

  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.ssh.private_key_path  = 'config/ssh/insecure_private_key'

  config.vm.box = 'centos/7'

  config.vm.provision "file", source: "config/etc/hosts", destination: "config/etc/hosts"
  config.vm.provision "file", source: "config/etc/resolv.conf", destination: "config/etc/resolv.conf"
  config.vm.provision "file", source: "scripts/files.sh", destination: "scripts/files.sh"
  config.vm.provision :shell, path: 'scripts/files.sh'

  # https://blog.centos.org/2019/07/updated-centos-vagrant-images-available-v1905-01/
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end


  config.vm.define 'master' do |master|
    master.vm.provider 'virtualbox' do |vm|
      vm.cpus = 2
      vm.memory = 2048
      vm.name = 'master'
    end
    master.vm.hostname = 'master'
    master.vm.network "private_network", ip: '192.168.234.230'
    master.vm.synced_folder "../src/", "/src", type: "sshfs", sshfs_opts_append: "-o nonempty"
  end

  config.vm.define 'web01' do |minion|
    minion.vm.provider 'virtualbox' do |vm|
      vm.cpus = 2
      vm.memory = 1024
      vm.name = 'web01'
    end
    minion.vm.hostname = 'web01'
    minion.vm.network "private_network", ip: '192.168.234.231'
  end

  config.vm.define 'compute01' do |minion|
    minion.vm.provider 'virtualbox' do |vm|
      vm.cpus = 2
      vm.memory = 1024
      vm.name = 'compute01'
    end
    minion.vm.hostname = 'compute01'
    minion.vm.network "private_network", ip: '192.168.234.232'
  end

  # config.vm.define 'compute02' do |minion|
  #   minion.vm.provider 'virtualbox' do |vm|
  #     vm.cpus = 2
  #     vm.memory = 1024
  #     vm.name = 'compute02'
  #   end
  #   minion.vm.hostname = 'compute02'
  #   minion.vm.network "private_network", ip: '192.168.234.233'
  # end

end
