- name: "Copy Files"
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'files/.bashrc', dest: '~/.bashrc' }
    - { src: 'files/etc/yum.conf', dest: '/etc/yum.conf' }
    - { src: 'files/.bash_aliases', dest: '/etc/profile.d/00-aliases.sh' }

- name: "Enable EPEL Repository"
  yum: pkg=epel-release state=installed

- name: Upgrade all packages, beside excluded ones
  yum:
    name: '*'
    state: latest
    exclude: kernel*, docker*, kubernetes*

- name: "Install Packages"
  yum: pkg={{ item.packages }} state=installed
  with_items:
    - environment: production
      packages:
        - bash-completion
        - git
        - htop
        - mc
        - nfs-utils
        - vim
    - environment: development
      packages:
        - bash-completion
        - git
        - htop
        - mc
        - net-tools
        - nfs-utils
        - nmap
        - vim
  when: item.environment == deployment
