- name: "Copy files related to kubernetes"
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'files/etc/selinux/config', dest: '/etc/selinux/config' }
    - { src: 'files/etc/profile.d/bashrc.sh', dest: '/etc/profile.d/bashrc.sh' }
    - { src: 'files/etc/modules-load.d/ip_vs.conf', dest: '/etc/modules-load.d/ip_vs.conf' }
    - { src: 'files/etc/modules-load.d/br_netfilter.conf', dest: '/etc/modules-load.d/br_netfilter.conf' }
    - { src: 'files/etc/sysctl.d/k8s.conf', dest: '/etc/sysctl.d/k8s.conf' }
    - { src: 'files/etc/yum.repos.d/kubernetes.repo', dest: '/etc/yum.repos.d/kubernetes.repo' }
    # - { src: 'files/10-kubeadm.conf', dest: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf' }


- name: "Disable swap"
  command: swapoff -a

- name: "Disable swap in fstab"
  replace:
    dest: /etc/fstab
    regexp: '^/swap'
    replace: '#/swap'

- name: "SELinux setenforce 0"
  selinux:
    policy: targeted
    state: permissive

  - name: "Add kernel modules"
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - ip_vs_sh
      - ip_vs_wrr
      - br_netfilter

- name: "Enable bridge-nf-call-iptables kernel module"
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: "Enable Kubernetes Worker Ports"
  firewalld:
    port: "{{ item.port }}/{{ item.type }}"
    permanent: true
    state: enabled
  with_items:
    - { port: 10250, type: tcp }

- name: "Reload sysctl"
  command: sysctl --system

- name: "Restart Firewall Service"
  service:
    name: firewalld
    state: reloaded
    enabled: yes

- name: "Install Kubernetes"
  yum:
    name:
      - kubectl-1.13.3-0
      - kubelet-1.13.3-0
      - kubeadm-1.13.3-0
      - ipvsadm
    state: latests
    disable_excludes: main

- name: "Reload daemon-reload Service"
  command: systemctl daemon-reload

- name: "Restart Kublet Service"
  systemd:
    name: kubelet
    state: restarted
    enabled: yes

- name: "Restart Docker Service"
  systemd:
    name: docker
    state: restarted
    enabled: yes
