- name: Creates /tmp/downloads directory
  file:
    path: /tmp/downloads
    state: directory

- name: Download helm-{{ helm_version }}-linux-amd64.tar.gz
  get_url:
      url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
      dest: /tmp/downloads/helm-{{ helm_version }}-linux-amd64.tar.gz

- name: Extract helm-{{ helm_version }}-linux-amd64.tar.gz
  unarchive:
    src: /tmp/downloads/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: /tmp/downloads
    remote_src: yes

- name: Copy Helm binary to /usr/local/bin/helm
  copy:
    src: /tmp/downloads/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: 0755
    remote_src: yes

- name: Delete /tmp/downloads directory
  file:
    path: /tmp/downloads
    state: absent
