- name: "Add Docker Repo"
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: "Enable Docker Edge Repo"
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: "Install Docker Dependencies"
  yum: pkg={{ item }} state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: "Install Docker"
  yum: pkg={{ item }} state=installed
  with_items:
    - containerd.io
    - docker-ce-18.09.2-3.el7

- name: "Add User vagrant To docker Group"
  user:
    name: vagrant
    groups: docker
    append: yes
  when: deployment == "development"

- name: "Install Docker Composer"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: yes
    mode: 0755

- name: "Install Docker Auto-complete"
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker.sh
    force: yes
    mode: 0755

- name: "Enable Ports for Docker and Docker Swarm"
  firewalld:
    port: "{{ item.port }}/{{ item.type }}"
    permanent: true
    state: enabled
  with_items:
    # Docker TLS link: https://docs.docker.com/engine/security/https/#secure-by-default
    - { port: 2376, type: tcp }
    - { port: 2377, type: tcp }
    # Swarm ports link: https://docs.docker.com/engine/swarm/ingress/
    - { port: 7946, type: tcp }
    - { port: 7946, type: udp }
    - { port: 4789, type: udp }
  when: deployment == "development"

- name: "Restart Firewall Service"
  service:
    name: firewalld
    state: reloaded
    enabled: yes
  when: deployment == "development"

- name: Enable docker service and ensure it is not masked
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: "Start Docker Service"
  service:
    name: docker
    state: started
    enabled: yes
