- name: "Add Docker Repo"
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: "Enable Docker Edge Repo"
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: "Install Docker Dependencies"
  yum: pkg={{ item }} state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: "Install Docker"
  yum: pkg=docker-ce state=latest

- name: "Add User vagrant To docker Group"
  user:
    name: vagrant
    groups: docker
    append: yes

- name: "Install Docker Composer"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: yes
    mode: 0755

- name: "Install Docker Auto-complete"
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker.sh
    force: yes
    mode: 0755

- name: "Enable Docker Ports"
  firewalld:
    port: "{{ item.port }}/{{ item.type }}"
    permanent: true
    state: enabled
  with_items:
    - { port: 2376, type: tcp }
    - { port: 2377, type: tcp }
    - { port: 7946, type: tcp }
    - { port: 7946, type: udp }
    - { port: 4789, type: udp }

- name: "Restart Firewall Service"
  service:
    name: firewalld
    state: reloaded
    enabled: yes

- name: "Start Docker Service"
  service:
    name: docker
    state: started
    enabled: yes
