---
# - hosts: all-dev
#   become: true
#   roles:
#     - common
#     - docker

- hosts: kubernetes-master-dev
  become: true
  roles:
    - kubernetes-master

- hosts: kubernetes-worker-dev
  become: true
  roles:
    - kubernetes-worker
