---
- hosts: all
  become: true
  roles:
    - common
    - docker

- hosts: master
  become: true
  roles:
    - nfs-master

- hosts: slave
  become: true
  roles:
    - nfs-slave

- hosts: kubernetes-master
  become: true
  roles:
    - kubernetes-master
    - kubernetes-traefik
    # - kubernetes-helm

- hosts: kubernetes-worker
  become: true
  roles:
    - kubernetes-worker

- hosts: kubernetes-client
  become: true
  roles:
    - kubernetes-client