---
- hosts: all
  become: true
  roles:
    - common

- hosts: nfs-master
  become: true
  roles:
    - nfs-master

- hosts: nfs-slave
  become: true
  roles:
    - nfs-slave

- hosts: kubernetes-cluster
  become: true
  roles:
    - docker
