---
- hosts: all-dev
  become: true
  roles:
    - common
    - docker

- hosts: master-dev
  become: true
  roles:
    - nfs-master

- hosts: slave-dev
  become: true
  roles:
    - nfs-slave

- hosts: kubernetes-master-dev
  become: true
  roles:
    - kubernetes-master
    - kubernetes-helm
    - kubernetes-traefik

- hosts: kubernetes-worker-dev
  become: true
  roles:
    - kubernetes-worker
