---
- hosts: all-dev
  become: true
  vars:
    deployment: "development"
  roles:
    - common
    - docker

# - hosts: kubernetes-master
#   become: true
#   roles:
#     - kubernetes-master
#
# - hosts: kubernetes-worker
#   become: true
#   roles:
#     - kubernetes-worker
