---
- hosts: all
  become: true
  roles:
    - common

- hosts: nfs-master
  become: true
  roles:
    - nfs-master

- hosts: nfs-slave
  become: true
  roles:
    - nfs-slave

- hosts: kubernetes-all
  become: true
  roles:
    - docker

- hosts: kubernetes-master
  become: true
  roles:
    - kubernetes-master
    - kubernetes-traefik
    # - kubernetes-helm

- hosts: kubernetes-worker
  become: true
  roles:
    - kubernetes-worker

- hosts: kubernetes-client
  become: true
  roles:
    - kubernetes-client