- name: Copy config files
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'files/etc/exports', dest: '/etc/exports' }

- name: Create nfs directories
  file:
    owner: vagrant
    group: vagrant
    path: "{{ item }}"
    state: directory
  with_items:
    - /nfs/www
    - /nfs/data

- name: Enable and start nfs related service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

- name: Enable and start 'firewalld' service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Enable nfs service on Firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - nfs
    - nfs3
    - mountd
    - rpc-bind

- name: Reload 'firewalld' service
  systemd:
    name: firewalld
    state: reloaded
