- name: Create /nfs/data directory
  file:
    path: /mnt/nfs/data
    owner: vagrant
    group: vagrant
    state: directory

- name: Enable and start 'rpcbind' service
  systemd:
    name: rpcbind
    state: started
    enabled: yes

- name: Enable and start 'firewalld' service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Mount nfs directories
  mount:
    name: /mnt/nfs/data
    opts: defaults,vers=3,intr
    fstype: nfs
    src: master:/nfs/data
    state: mounted
